export * from './statistic.api'
export * from './getAllEventsOfStatistic.query'
export * from './getAllProofsOfStatistic.query'
export * from './getAllRegisteredStudentsOfStatistic.query'
export * from './getAllAttendanceStudentsOfStatistic.query'
export * from './getTotalStatistics.query'
